export default function getCustomMapStyle() {
  return {
    "version": 8,
    "name": "cs-base-map",
    "metadata": {
      "mapbox:autocomposite": true,
      "mapbox:type": "template",
      "mapbox:sdk-support": {
        "android": "10.0.0",
        "ios": "10.0.0",
        "js": "2.3.0",
      },
      "mapbox:uiParadigm": "components",
      "mapbox:groups": {
        "Administrative boundaries, admin": {
          "name": "Administrative boundaries, admin",
          "collapsed": true,
        },
        "Place labels, place-labels": {
          "name": "Place labels, place-labels",
          "collapsed": true,
        },
      },
      "mapbox:decompiler": {
        "id": "ckx4rve8e4g3h15p5ng8y8tzp",
        "strata": [
          {
            "id": "ckx4krhfm496215p5p2si32uw",
            "order": [
              "mapbox-satellite",
              "water",
              ["admin-boundaries", "admin"],
              ["place-labels", "place-labels"],
            ],
          },
        ],
        "components": {
          "admin-boundaries": "11.1.1",
          "place-labels": "11.1.1",
        },
        "propConfig": {
          "admin-boundaries": {
            "colorBase": "hsla(200, 19%, 18%, 0.39)",
            "colorPlaceLabel": "hsl(0, 0%, 100%)",
            "admin1": false,
            "colorAdminBoundary": "hsla(0, 0%, 100%, 0.35)",
            "worldview": "US",
          },
          "place-labels": {
            "states": false,
            "countriesFont": [
              "IBM Plex Sans SemiBold",
              "Arial Unicode MS Regular",
            ],
            "settlementSubdivisions": false,
            "colorPlaceLabel": "hsl(0, 0%, 100%)",
            "statesFont": ["IBM Plex Sans SemiBold", "Arial Unicode MS Bold"],
            "countryLabelStyle": "Text and icon",
            "colorBase": "hsla(200, 19%, 18%, 0.39)",
            "countries": false,
            "worldview": "US",
            "settlementsMinorFont": [
              "IBM Plex Sans SemiBold",
              "Arial Unicode MS Regular",
            ],
            "settlementsMajorFont": [
              "IBM Plex Sans Bold",
              "Arial Unicode MS Regular",
            ],
            "settlementsDensity": 1,
            "settlementSubdivisionsFont": [
              "IBM Plex Sans SemiBold",
              "Arial Unicode MS Regular",
            ],
          },
        },
      },
    },
    "center": [6.818318212136092, 47.49206023840209],
    "zoom": 5.132514078568663,
    "bearing": 0,
    "pitch": 0,
    "light": { "anchor": "viewport", "color": "hsl(0, 0%, 100%)" },
    "sources": {
      "mapbox://mapbox.satellite": {
        "url": "mapbox://mapbox.satellite",
        "type": "raster",
        "tileSize": 256,
      },
      "composite": {
        "url": "mapbox://mapbox.mapbox-streets-v8",
        "type": "vector",
      },
    },
    "sprite":
      "mapbox://sprites/climatescope/ckx4rve8e4g3h15p5ng8y8tzp/ephaas7u9k7qsgvb1e9dfc0k4",
    "glyphs": "mapbox://fonts/climatescope/{fontstack}/{range}.pbf",
    "projection": { "name": "equalEarth" },
    "layers": [
      {
        "id": "mapbox-satellite",
        "type": "raster",
        "source": "mapbox://mapbox.satellite",
        "paint": { "raster-opacity": 1, "raster-saturation": -0.4 },
      },
      {
        "id": "water",
        "type": "fill",
        "source": "composite",
        "source-layer": "water",
        "layout": {},
        "paint": { "fill-color": "#002d33", "fill-outline-color": "#002024" },
      },
      // {
      //   "id": "admin-0-boundary-bg",
      //   "type": "line",
      //   "metadata": {
      //     "mapbox:featureComponent": "admin-boundaries",
      //     "mapbox:group": "Administrative boundaries, admin",
      //   },
      //   "source": "composite",
      //   "source-layer": "admin",
      //   "minzoom": 1,
      //   "filter": [
      //     "all",
      //     ["==", ["get", "admin_level"], 0],
      //     ["==", ["get", "maritime"], "false"],
      //     ["match", ["get", "worldview"], ["all", "US"], true, false],
      //   ],
      //   "layout": {},
      //   "paint": {
      //     "line-width": ["interpolate", ["linear"], ["zoom"], 3, 3.5, 10, 8],
      //     "line-color": [
      //       "interpolate",
      //       ["linear"],
      //       ["zoom"],
      //       6,
      //       "hsla(200, 17%, 17%, 0.39)",
      //       8,
      //       "hsla(0, 0%, 0%, 0.35)",
      //     ],
      //     "line-opacity": ["interpolate", ["linear"], ["zoom"], 3, 0, 4, 0.5],
      //     "line-blur": ["interpolate", ["linear"], ["zoom"], 3, 0, 10, 2],
      //   },
      // },
      // {
      //   "id": "admin-0-boundary",
      //   "type": "line",
      //   "metadata": {
      //     "mapbox:featureComponent": "admin-boundaries",
      //     "mapbox:group": "Administrative boundaries, admin",
      //   },
      //   "source": "composite",
      //   "source-layer": "admin",
      //   "minzoom": 1,
      //   "filter": [
      //     "all",
      //     ["==", ["get", "admin_level"], 0],
      //     ["==", ["get", "disputed"], "false"],
      //     ["==", ["get", "maritime"], "false"],
      //     ["match", ["get", "worldview"], ["all", "US"], true, false],
      //   ],
      //   "layout": { "line-join": "round", "line-cap": "round" },
      //   "paint": {
      //     "line-color": "hsla(0, 0%, 100%, 0.35)",
      //     "line-width": ["interpolate", ["linear"], ["zoom"], 3, 0.5, 10, 2],
      //     "line-dasharray": [10, 0],
      //   },
      // },
      // {
      //   "id": "admin-0-boundary-disputed",
      //   "type": "line",
      //   "metadata": {
      //     "mapbox:featureComponent": "admin-boundaries",
      //     "mapbox:group": "Administrative boundaries, admin",
      //   },
      //   "source": "composite",
      //   "source-layer": "admin",
      //   "minzoom": 1,
      //   "filter": [
      //     "all",
      //     ["==", ["get", "disputed"], "true"],
      //     ["==", ["get", "admin_level"], 0],
      //     ["==", ["get", "maritime"], "false"],
      //     ["match", ["get", "worldview"], ["all", "US"], true, false],
      //   ],
      //   "layout": { "line-join": "round" },
      //   "paint": {
      //     "line-color": "hsla(0, 0%, 100%, 0.35)",
      //     "line-width": ["interpolate", ["linear"], ["zoom"], 3, 0.5, 10, 2],
      //     "line-dasharray": [
      //       "step",
      //       ["zoom"],
      //       ["literal", [3.25, 3.25]],
      //       6,
      //       ["literal", [2.5, 2.5]],
      //       7,
      //       ["literal", [2, 2.25]],
      //       8,
      //       ["literal", [1.75, 2]],
      //     ],
      //   },
      // },
      {
        "id": "settlement-minor-label",
        "type": "symbol",
        "metadata": {
          "mapbox:featureComponent": "place-labels",
          "mapbox:group": "Place labels, place-labels",
        },
        "source": "composite",
        "source-layer": "place_label",
        "minzoom": 3,
        "maxzoom": 13,
        "filter": [
          "all",
          ["<=", ["get", "filterrank"], 1],
          [
            "match",
            ["get", "class"],
            "settlement",
            ["match", ["get", "worldview"], ["all", "US"], true, false],
            "disputed_settlement",
            [
              "all",
              ["==", ["get", "disputed"], "true"],
              ["match", ["get", "worldview"], ["all", "US"], true, false],
            ],
            false,
          ],
          [
            "step",
            ["zoom"],
            [">", ["get", "symbolrank"], 6],
            4,
            [">=", ["get", "symbolrank"], 7],
            6,
            [">=", ["get", "symbolrank"], 8],
            7,
            [">=", ["get", "symbolrank"], 10],
            10,
            [">=", ["get", "symbolrank"], 11],
            11,
            [">=", ["get", "symbolrank"], 13],
            12,
            [">=", ["get", "symbolrank"], 15],
          ],
        ],
        "layout": {
          "text-line-height": 1.1,
          "text-size": [
            "interpolate",
            ["cubic-bezier", 0.2, 0, 0.9, 1],
            ["zoom"],
            3,
            [
              "step",
              ["get", "symbolrank"],
              12,
              9,
              11,
              10,
              10.5,
              12,
              9.5,
              14,
              8.5,
              16,
              6.5,
              17,
              4,
            ],
            13,
            [
              "step",
              ["get", "symbolrank"],
              23,
              9,
              21,
              10,
              19,
              11,
              17,
              12,
              16,
              13,
              15,
              15,
              13,
            ],
          ],
          "text-radial-offset": [
            "step",
            ["zoom"],
            ["match", ["get", "capital"], 2, 0.6, 0.55],
            8,
            0,
          ],
          "icon-image": [
            "step",
            ["zoom"],
            [
              "case",
              ["==", ["get", "capital"], 2],
              "border-dot-13",
              [
                "step",
                ["get", "symbolrank"],
                "dot-11",
                9,
                "dot-10",
                11,
                "dot-9",
              ],
            ],
            8,
            "",
          ],
          "text-font": ["IBM Plex Sans SemiBold", "Arial Unicode MS Regular"],
          "text-justify": "auto",
          "text-anchor": [
            "step",
            ["zoom"],
            ["get", "text_anchor"],
            8,
            "center",
          ],
          "text-field": ["coalesce", ["get", "name_en"], ["get", "name"]],
          "text-max-width": 7,
        },
        "paint": {
          "text-color": "hsl(0, 0%, 95%)",
          "text-halo-color": "hsla(200, 24%, 3%, 0.39)",
          "text-halo-width": 1,
          "text-halo-blur": 1,
        },
      },
      {
        "id": "settlement-major-label",
        "type": "symbol",
        "metadata": {
          "mapbox:featureComponent": "place-labels",
          "mapbox:group": "Place labels, place-labels",
        },
        "source": "composite",
        "source-layer": "place_label",
        "minzoom": 3,
        "maxzoom": 15,
        "filter": [
          "all",
          ["<=", ["get", "filterrank"], 1],
          [
            "match",
            ["get", "class"],
            "settlement",
            ["match", ["get", "worldview"], ["all", "US"], true, false],
            "disputed_settlement",
            [
              "all",
              ["==", ["get", "disputed"], "true"],
              ["match", ["get", "worldview"], ["all", "US"], true, false],
            ],
            false,
          ],
          [
            "step",
            ["zoom"],
            false,
            3,
            ["<=", ["get", "symbolrank"], 6],
            4,
            ["<", ["get", "symbolrank"], 7],
            6,
            ["<", ["get", "symbolrank"], 8],
            7,
            ["<", ["get", "symbolrank"], 10],
            10,
            ["<", ["get", "symbolrank"], 11],
            11,
            ["<", ["get", "symbolrank"], 13],
            12,
            ["<", ["get", "symbolrank"], 15],
            13,
            [">=", ["get", "symbolrank"], 11],
            14,
            [">=", ["get", "symbolrank"], 15],
          ],
        ],
        "layout": {
          "text-line-height": 1.1,
          "text-size": [
            "interpolate",
            ["cubic-bezier", 0.2, 0, 0.9, 1],
            ["zoom"],
            3,
            ["step", ["get", "symbolrank"], 13, 6, 12],
            6,
            ["step", ["get", "symbolrank"], 16, 6, 15, 7, 14],
            8,
            ["step", ["get", "symbolrank"], 18, 9, 17, 10, 15],
            15,
            [
              "step",
              ["get", "symbolrank"],
              23,
              9,
              22,
              10,
              20,
              11,
              18,
              12,
              16,
              13,
              15,
              15,
              13,
            ],
          ],
          "text-radial-offset": [
            "step",
            ["zoom"],
            ["match", ["get", "capital"], 2, 0.6, 0.55],
            8,
            0,
          ],
          "icon-image": [
            "step",
            ["zoom"],
            [
              "case",
              ["==", ["get", "capital"], 2],
              "border-dot-13",
              [
                "step",
                ["get", "symbolrank"],
                "dot-11",
                9,
                "dot-10",
                11,
                "dot-9",
              ],
            ],
            8,
            "",
          ],
          "text-font": ["IBM Plex Sans Bold", "Arial Unicode MS Regular"],
          "text-justify": [
            "step",
            ["zoom"],
            [
              "match",
              ["get", "text_anchor"],
              ["left", "bottom-left", "top-left"],
              "left",
              ["right", "bottom-right", "top-right"],
              "right",
              "center",
            ],
            8,
            "center",
          ],
          "text-anchor": [
            "step",
            ["zoom"],
            ["get", "text_anchor"],
            8,
            "center",
          ],
          "text-field": ["coalesce", ["get", "name_en"], ["get", "name"]],
          "text-max-width": 7,
        },
        "paint": {
          "text-color": "hsl(0, 0%, 95%)",
          "text-halo-color": "hsla(200, 24%, 3%, 0.39)",
          "text-halo-width": 1,
          "text-halo-blur": 1,
        },
      },
    ],
    "created": "2021-12-13T14:29:38.150Z",
    "modified": "2021-12-13T14:36:28.314Z",
    "id": "ckx4rve8e4g3h15p5ng8y8tzp",
    "owner": "climatescope",
    "visibility": "private",
    "protected": false,
    "draft": false,
  }
}
