export const projections = [
  {
    id: "europe",
    name: "albers",
    center: [10, 30],
    parallels: [43, 62],
    regions: ["eu"],
    countries: ["ch", "de", "fr", "it", "nl"],
  },
  {
    id: "russia",
    name: "albers",
    center: [100, 58],
    parallels: [46, 70],
    regions: [],
    countries: ["ru"],
  },
  {
    id: "usa",
    name: "albers",
    center: [-95, 36.75],
    parallels: [27.25, 46.25],
    regions: ["northamer"],
    countries: ["us"],
  },
  {
    id: "central-america",
    name: "albers",
    center: [-89, 19],
    parallels: [8.3333333, 29.6666667],
    regions: [],
    countries: ["mx"],
  },
  {
    id: "south-america-north",
    name: "mercator",
    center: [-61, -17],
    regions: ["amer", "latam"],
    countries: ["co", "br"],
  },
  {
    id: "south-america-south",
    name: "albers",
    center: [-62, -36],
    parallels: [-50, -22],
    regions: [],
    countries: ["ar", "cl", "uy"],
  },
  {
    id: "africa-center",
    name: "mercator",
    center: [28, -19.5],
    parallels: [-32.5, -6.5],
    regions: ["ssa"],
    countries: ["cd"],
  },
  {
    id: "africa-south",
    name: "albers",
    center: [28, -19.5],
    parallels: [-32.5, -6.5],
    regions: [],
    countries: ["za"],
  },
  {
    id: "africa-north",
    name: "albers",
    center: [14, 19.5],
    parallels: [6.5, 32.5],
    regions: [],
    countries: ["ng"],
  },
  {
    id: "middle-east",
    name: "albers",
    center: [53, 28.75],
    parallels: [17.25, 40.25],
    regions: ["mena"],
    countries: ["af"],
  },
  {
    id: "india",
    name: "albers",
    center: [80, 20.25],
    parallels: [9.75, 30.75],
    regions: [],
    countries: ["in"],
  },
  {
    id: "southeast-asia",
    name: "mercator",
    center: [118, 9],
    regions: ["apac"],
    countries: ["id"],
  },
  {
    id: "china",
    name: "albers",
    center: [105, 36],
    parallels: [23.5, 48.5],
    regions: [],
    countries: ["cn"],
  },
  {
    id: "east-asia",
    name: "albers",
    center: [135, 37.5],
    parallels: [30.5, 44.5],
    regions: ["asia"],
    countries: ["jp"],
  },
  {
    id: "australia",
    name: "albers",
    center: [135, -28],
    parallels: [-40, -16],
    regions: [],
    countries: ["au"],
  },
  {
    id: "oceania",
    name: "albers",
    center: [155, -26.4],
    parallels: [-40.8, -12],
    regions: [],
    countries: ["nz"],
  },
  {
    id: "canada",
    name: "albers",
    center: [-97, 57.5],
    parallels: [46.5, 68.5],
    regions: [],
    countries: ["ca"],
  },
]

export const getProjection = (iso, region) => {
  const { name, center, parallels } =
    projections.find((s) => s.countries.includes(iso.toLowerCase())) ||
    projections.find((s) => s.regions.includes(region)) ||
    projections[0]
  return { name, center, parallels }
}
