# Deploy the site to AWS S3 on a push to the 'main' branch

name: Deploy GH Pages

on:
  push:
    branches:
    - 'master'

env:
  NODE: 18

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ env.NODE }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE }}

      - name: Cache node_modules
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}

      - name: Cache out
        uses: actions/cache@v3
        id: cache-out
        with:
          path: out
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Install
        run: npm install

      - name: Build
        run: npm export
        env:
          SITE_URL: https://www.global-climatescope.org/
          MAILCHIMP_ADDRESS: ${{ secrets.MAILCHIMP_ADDRESS }}
          MAPBOX_TOKEN: ${{ secrets.MB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Restore out cache
        uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: out
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ github.sha }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          publish_branch: gh-pages
